name: auto_chat_action
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/xooniverse/AutoChatAction

environment:
  sdk: ^3.4.4

dependencies:
  televerse: ^1.19.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
